apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 1
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template: 
    metadata:
      labels:
        app: spring-app
    spec:
      terminationGracePeriodSeconds: 30
      dnsConfig:  
        options:  
        - name: single-request-reopen
      containers:
      - name: spring-app
        image: #{ACRLoginServer}#:#{ImageName}#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: default-port 
        resources:
          requests: 
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: default
  labels:
    app: spring-app
spec:
  type: ClusterIP
  selector:
    app: spring-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
